DROP DATABASE IF EXISTS DBCOMPRAPARCELADA;
CREATE DATABASE DBCOMPRAPARCELADA;
USE DBCOMPRAPARCELADA;

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT	
	, VALOR_TOTAL NUMERIC(8,2)
	, QTDE_PARCELA INT
	, DT_COMPRA DATE
    	, PRIMARY KEY (IDCOMPRA)
);

CREATE TABLE PARCELA(
	IDPARCELA INT NOT NULL AUTO_INCREMENT
    	, IDCOMPRA INT NOT NULL
    	, NUMERO INT
    	, DT_VENCIMENTO DATE
    	, VALOR NUMERIC(8,2)
    	, PRIMARY KEY (IDPARCELA)
    	, FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
);


-- 1 Criar um procedimento para incluir a compra e suas parcelas

-- 2 O vencimento das parcelas de iniciar no proximo mes da compra, e sendo acrescido de 1 mês
 
-- 3 Validar o valor final das parcelas se está correta com o valor da compra



DELIMITER $$

CREATE PROCEDURE STP_LANCAR_COMPRA(pVALOR_TOTAL NUMERIC(8,2), pQTDE_PARCELA INT) BEGIN
DECLARE CONT INT;
DECLARE vCOMPRA INT;
DECLARE vVALOR_PARCELA NUMERIC(8,2);
DECLARE vSOMA_PARCELAS NUMERIC(8,2);
DECLARE vULTIMA_PARCELA INT;

INSERT INTO COMPRA(VALOR_TOTAL,QTDE_PARCELA,DT_COMPRA)
VALUES(pVALOR_TOTAL,pQTDE_PARCELA,NOW());

SET  vCOMPRA = last_insert_id();
SET CONT = 1;
SET vVALOR_PARCELA= pVALOR_TOTAL/pQTDE_PARCELA;


WHILE CONT<=pQTDE_PARCELA DO

INSERT INTO PARCELA(IDCOMPRA,NUMERO,DT_VENCIMENTO, VALOR)
VALUES(vCOMPRA,CONT,DATE_ADD(NOW(),INTERVAL CONT MONTH), vVALOR_PARCELA );
SET CONT = CONT + 1;



END WHILE;

SELECT MAX(IDPARCELA), SUM(VALOR)
INTO vULTIMA_PARCELA, vSOMA_PARCELAS
FROM PARCELA
WHERE IDCOMPRA=CONT;

UPDATE PARCELA
SET VALOR = VALOR + (pVALOR_TOTAL - vSOMA_PARCELAS)
WHERE IDPARCELA = vULTIMA_PARCELA;  
END $$


DELIMITER ;


CALL STP_LANCAR_COMPRA(54000,48);
CALL STP_LANCAR_COMPRA(100,5);
CALL STP_LANCAR_COMPRA(10000,12);

CALL STP_LANCAR_COMPRA(50, 3);

SELECT * FROM COMPRA;
SELECT * FROM PARCELA WHERE IDCOMPRA = 6;

SELECT * FROM COMPRA;
SELECT * FROM PARCELA;
