SET GLOBAL log_bin_trust_function_creators = 1;
drop database if exists DBEXERCICIO18;
CREATE DATABASE DBEXERCICIO18;
USE DBEXERCICIO18;

DELIMITER $$
CREATE FUNCTION FN_ADICAO (pNUMERO_A INT,pNUMERO_B INT) RETURNS INT
BEGIN

DECLARE vRESULTADO INT;
SET vRESULTADO=pNUMERO_A+pNUMERO_B;
RETURN vRESULTADO;

END $$

CREATE FUNCTION FN_SUBTRACAO (pNUMERO_A INT,pNUMERO_B INT) RETURNS INT
BEGIN

DECLARE vRESULTADO INT;
SET vRESULTADO=pNUMERO_A-pNUMERO_B;
RETURN vRESULTADO;

END $$

CREATE FUNCTION FN_DIVISAO (pNUMERO_A INT,pNUMERO_B INT) RETURNS NUMERIC(8,2)
BEGIN

DECLARE vRESULTADO NUMERIC(8,2);
SET vRESULTADO=pNUMERO_A/pNUMERO_B;
RETURN vRESULTADO;

END $$

CREATE FUNCTION FN_MULTIPLICACAO (pNUMERO_A INT,pNUMERO_B INT) RETURNS INT
BEGIN

DECLARE vRESULTADO INT;
SET vRESULTADO=pNUMERO_A*pNUMERO_B;
RETURN vRESULTADO;

END $$

CREATE FUNCTION FN_CALCULADORA(pNUMERO_A INT,pNUMERO_B INT, pOPERADOR CHAR(1)) RETURNS NUMERIC(8,2)
BEGIN
DECLARE vRESULTADO NUMERIC(8,2);

CASE pOPERADOR
WHEN '+'THEN SET vRESULTADO=FN_ADICAO(pNUMERO_A,pNUMERO_B); 
WHEN '-'THEN SET vRESULTADO=FN_SUBTRACAO(pNUMERO_A,pNUMERO_B); 
WHEN '/'THEN SET vRESULTADO=FN_DIVISAO(pNUMERO_A,pNUMERO_B); 
WHEN '*'THEN SET vRESULTADO=FN_MULTIPLICACAO(pNUMERO_A,pNUMERO_B); 
ELSE SET vRESULTADO = NULL;
END CASE;

RETURN vRESULTADO;
END $$

CREATE FUNCTION FN_PRIMO(pNUMERO INT) RETURNS CHAR(3)
BEGIN
DECLARE vRESULTADO CHAR(3);
DECLARE vCONTADOR INT;

SET vRESULTADO = 'SIM';
SET vCONTADOR=PNUMERO-1;

WHILE((vCONTADOR>1)AND(vRESULTADO='SIM')) DO

IF((pNUMERO%VCONTADOR)=0)THEN
SET vRESULTADO='NAO';
END IF;

SET vCONTADOR=vCONTADOR-1;
END WHILE;
RETURN vRESULTADO;

END $$
CREATE FUNCTION FN_IDADE(pDT_NASCIMENTO DATE) RETURNS INT
BEGIN

DECLARE IDADE INT;
SET IDADE=YEAR(NOW())-YEAR(pDT_NACIMENTO);

IF(DATE_ADD(pDT_NASCIMENTO,INTERVAL IDADE YEAR)>NOW())THEN
SET IDADE=IDADE-1;
END IF;

RETURN IDADE;
END $$
CREATE FUNCTION FN_NIVER (pDT_NASCIMENTO DATE) RETURNS DATE
BEGIN

	 DECLARE vIDADE INT;
     DECLARE vNIVER DATE;
     
     SET vIDADE = YEAR(NOW()) - YEAR(pDT_NASCIMENTO);     
     SET vNIVER = DATE_ADD(pDT_NASCIMENTO, INTERVAL vIDADE YEAR);
     
     IF (vNIVER < NOW())THEN
		SET vNIVER = DATE_ADD(vNIVER, INTERVAL 1 YEAR);
     END IF ;

	RETURN vNIVER;
    
END $$
DELIMITER ;
SELECT FN_NIVER('1981-08-08');
SELECT FN_ADICAO(2,3);
SELECT FN_SUBTRACAO(2,3);
SELECT FN_DIVISAO(2,3);
SELECT FN_MULTIPLICACAO(2,3);
SELECT FN_CALCULADORA(2,5,'*');
SELECT FN_PRIMO(5);
SELECT FN_IDADE(2021/11/11);