SET SQL_SAFE_UPDATES = 0;

DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE PRODUTO (
IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , VALOR_EURO  NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

/*
QUESTÃO:
1. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR E EURO DEVE SER CALCULADO

Valor para conversão 1 Real = 3,9005 Dólar
Valor para conversão 1 Real = 4,3684 Euro
*/



DELIMITER $$

CREATE TRIGGER TR_PRODUTO_BI BEFORE INSERT ON PRODUTO FOR EACH ROW BEGIN

	DECLARE vCAL_VALOR_REAL NUMERIC(8,2);
    DECLARE vCAL_VALOR_DOLAR NUMERIC(8,2);
    DECLARE vCAL_VALOR_EURO  NUMERIC(8,2);

	-- TESTAR SE TODOS NULOS
    IF NEW.VALOR_REAL IS NULL AND NEW.VALOR_DOLAR IS NULL AND NEW.VALOR_EURO IS NULL THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PELO MENOS UM VALOR DEVE SER INFORMADO';        
    ELSE
		-- IDENTIFICAR QUAL FOI INFORMADO
		IF NEW.VALOR_REAL IS NOT NULL THEN
			SET vCAL_VALOR_REAL = NEW.VALOR_REAL;
			SET vCAL_VALOR_DOLAR = NEW.VALOR_REAL/4.22;
			SET vCAL_VALOR_EURO = NEW.VALOR_REAL/4.67;        
		ELSEIF NEW.VALOR_DOLAR IS NOT NULL THEN
			SET vCAL_VALOR_REAL = NEW.VALOR_DOLAR * 4.22;
			SET vCAL_VALOR_DOLAR = NEW.VALOR_DOLAR;
			SET vCAL_VALOR_EURO = vCAL_VALOR_REAL/4.67;        
		ELSEIF NEW.VALOR_EURO IS NOT NULL THEN
			SET vCAL_VALOR_REAL = NEW.VALOR_EURO * 4.67;
			SET vCAL_VALOR_DOLAR = vCAL_VALOR_REAL/4.22;
			SET vCAL_VALOR_EURO = NEW.VALOR_EURO; 
        END IF;
        
        IF NOT ( IFNULL(NEW.VALOR_REAL, vCAL_VALOR_REAL) = vCAL_VALOR_REAL AND
				 IFNULL(NEW.VALOR_DOLAR, vCAL_VALOR_DOLAR) = vCAL_VALOR_DOLAR AND
				IFNULL(NEW.VALOR_EURO, vCAL_VALOR_EURO) = vCAL_VALOR_EURO) THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'FOI INFORMADO VALORES DIFERENTES'; 
		ELSE
			SET NEW.VALOR_REAL = vCAL_VALOR_REAL;
			SET NEW.VALOR_DOLAR = vCAL_VALOR_DOLAR;
			SET NEW.VALOR_EURO = vCAL_VALOR_EURO; 
		END IF;    
    END IF;
   

END $$

DELIMITER ;


SELECT * FROM PRODUTO;


INSERT INTO PRODUTO(NOME,VALOR_REAL) VALUES('PEPSI', 8);
INSERT INTO PRODUTO(NOME,VALOR_EURO) VALUES('COCA-COLA',1.5);
INSERT INTO PRODUTO(NOME,VALOR_DOLAR) VALUES('MAÇA',2.25);
INSERT INTO PRODUTO(NOME) VALUES('LARANJA');
INSERT INTO PRODUTO(NOME,VALOR_REAL, VALOR_DOLAR) VALUES('PEPSI 3', 8, 1.70);



